// Curated 5-letter word list for Wordle
// Answers — common, well-known words
export const ANSWER_WORDS: string[] = [
  "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult",
  "after", "again", "agent", "agree", "ahead", "alarm", "album", "alert",
  "alike", "alive", "alley", "allow", "alone", "along", "alter", "angel",
  "anger", "angle", "angry", "anime", "annex", "antic", "anvil", "apart",
  "apple", "apply", "arena", "argue", "arise", "armor", "aroma", "arose",
  "array", "arrow", "aside", "asked", "asset", "atlas", "attic", "audit",
  "avail", "avid",  "avoid", "awake", "award", "aware", "awful", "badly",
  "baker", "basic", "basis", "batch", "beach", "began", "begin", "being",
  "below", "bench", "bible", "birth", "black", "blade", "blame", "bland",
  "blank", "blast", "blaze", "bleed", "blend", "bless", "blind", "block",
  "blood", "bloom", "blown", "blues", "blunt", "blush", "board", "bonus",
  "boost", "booth", "bound", "brain", "brand", "brave", "bread", "break",
  "breed", "brick", "bride", "brief", "bring", "broad", "broke", "brook",
  "brown", "brush", "buddy", "built", "burst", "buyer", "camel", "candy",
  "carry", "catch", "cause", "chain", "chair", "chaos", "charm", "chart",
  "chase", "cheap", "check", "cheek", "chess", "chest", "chief", "child",
  "chore", "chose", "civic", "civil", "claim", "clash", "class", "clean",
  "clear", "clerk", "click", "cliff", "climb", "cling", "clock", "clone",
  "close", "cloth", "cloud", "clout", "coach", "coast", "count", "court",
  "cover", "crack", "craft", "crash", "crazy", "cream", "creek", "crime",
  "crisp", "cross", "crowd", "crown", "cruel", "crush", "curve", "cycle",
  "daily", "dance", "datum", "dealt", "death", "debut", "delay", "delta",
  "dense", "depot", "depth", "devil", "dirty", "disco", "ditch", "dodge",
  "doing", "doubt", "dough", "draft", "drain", "drama", "drank", "drawn",
  "dread", "dream", "dress", "drift", "drink", "drive", "drove", "drunk",
  "dryer", "dying", "eager", "earth", "eight", "elite", "empty", "enemy",
  "enjoy", "enter", "entry", "equal", "essay", "event", "every", "exact",
  "exist", "extra", "faint", "faith", "false", "fancy", "fatal", "fault",
  "feast", "fence", "fever", "fewer", "fiber", "field", "fifth", "fifty",
  "fight", "final", "first", "fixed", "flame", "flash", "flesh", "float",
  "flock", "flood", "floor", "flour", "fluid", "flush", "focus", "force",
  "forge", "forth", "forum", "found", "frame", "frank", "fraud", "freed",
  "fresh", "front", "frost", "froze", "fruit", "fully", "funny", "giant",
  "given", "glare", "glass", "gleam", "glide", "gloom", "gloss", "glove",
  "going", "grace", "grade", "grain", "grand", "grant", "grape", "grasp",
  "grass", "grave", "great", "green", "greet", "grief", "grill", "grind",
  "groan", "gross", "group", "grout", "grown", "guard", "guess", "guest",
  "guide", "guild", "guile", "guilt", "guise", "gusto", "habit", "happy",
  "harsh", "haven", "heart", "heavy", "hedge", "hence", "hinge", "hoist",
  "honor", "horse", "hotel", "hound", "house", "human", "humor", "hurry",
  "hyper", "ideal", "image", "imply", "inbox", "index", "indie", "infer",
  "inner", "input", "inter", "intro", "irony", "ivory", "jewel", "joint",
  "judge", "juice", "juicy", "jumpy", "karma", "kayak", "knock", "known",
  "label", "large", "laser", "later", "laugh", "layer", "learn", "lease",
  "leave", "legal", "level", "light", "limit", "linen", "liver", "local",
  "lodge", "logic", "loose", "lover", "lower", "lucky", "lunar", "lying",
  "magic", "major", "maker", "manor", "maple", "march", "masse", "match",
  "mayor", "media", "mercy", "merge", "merit", "metal", "minor", "minus",
  "mixed", "model", "money", "month", "moral", "motor", "motto", "mould",
  "mount", "mouse", "mouth", "moved", "movie", "multi", "music", "naive",
  "naval", "nerve", "never", "night", "ninja", "noble", "noise", "north",
  "noted", "novel", "nurse", "occur", "ocean", "offer", "often", "older",
  "olive", "onset", "orbit", "order", "other", "ought", "outer", "owned",
  "owner", "oxide", "ozone", "paint", "panel", "panic", "paper", "party",
  "pasta", "patch", "pause", "peace", "pearl", "penny", "phase", "phone",
  "photo", "piano", "pilot", "pitch", "pixel", "pizza", "place", "plain",
  "plane", "plant", "plate", "plaza", "pluck", "plumb", "plume", "plunge",
  "point", "polar", "pound", "power", "press", "price", "pride", "prime",
  "print", "prior", "prize", "probe", "prone", "proof", "prose", "proud",
  "prove", "proxy", "pulse", "pupil", "purse", "queen", "quest", "queue",
  "quick", "quiet", "quota", "quote", "rabbi", "radar", "radio", "rainy",
  "rally", "ranch", "range", "rapid", "ratio", "reach", "ready", "realm",
  "rebel", "refer", "reign", "relax", "repay", "repel", "reply", "reset",
  "rider", "ridge", "rifle", "right", "risky", "rival", "river", "robin",
  "rocky", "roger", "roman", "rouge", "rough", "round", "route", "royal",
  "rugby", "ruler", "rural", "sadly", "saint", "salad", "sauce", "scale",
  "scare", "scene", "scope", "score", "scout", "seize", "sense", "seven",
  "shade", "shake", "shall", "shame", "shape", "share", "shark", "sharp",
  "shift", "shine", "shirt", "shock", "short", "shout", "sight", "silly",
  "since", "sixth", "sixty", "skill", "skull", "slash", "slate", "sleep",
  "slice", "slide", "slope", "smart", "smell", "smile", "smoke", "snake",
  "solar", "solid", "solve", "sorry", "sound", "south", "space", "spark",
  "speak", "spend", "spice", "spill", "spine", "spite", "split", "spoke",
  "spoon", "sport", "spray", "squad", "stack", "staff", "stage", "stain",
  "stake", "stale", "stand", "stark", "start", "state", "stays", "steam",
  "steel", "steep", "steer", "stern", "stick", "stiff", "still", "stock",
  "stone", "stood", "storm", "story", "stove", "strap", "straw", "strip",
  "study", "style", "sugar", "suite", "super", "surge", "swamp", "swear",
  "sweat", "sweep", "swept", "swift", "swing", "swore", "sword", "sworn",
  "syrup", "table", "taken", "taste", "teach", "tears", "tense", "tenth",
  "terms", "theft", "their", "theme", "thick", "thing", "think", "third",
  "thorn", "those", "three", "threw", "throw", "tiger", "tight", "timer",
  "tired", "title", "today", "token", "tooth", "topic", "total", "touch",
  "tough", "towel", "tower", "toxic", "trace", "track", "trade", "trail",
  "train", "trait", "trash", "treat", "trend", "trial", "tribe", "trick",
  "tried", "troop", "truck", "truly", "trump", "trunk", "trust", "truth",
  "tumor", "tuner", "tutor", "twice", "twist", "tying", "ultra", "uncle",
  "under", "unify", "union", "unite", "unity", "until", "upper", "urban",
  "usage", "usual", "utter", "valid", "value", "valve", "vault", "video",
  "vigor", "viral", "virus", "visit", "vital", "vivid", "voice", "voter",
  "vague", "waste", "watch", "water", "weary", "weave", "weird", "whale",
  "wheat", "wheel", "where", "which", "while", "white", "whole", "whose",
  "wider", "witch", "woman", "women", "world", "worry", "worse", "worst",
  "worth", "would", "wound", "wrath", "wrist", "wrote", "yacht", "yield",
  "young", "youth", "zebra", "zoned",
];

// Extended valid guess words (answers are always valid guesses too)
export const VALID_GUESSES: Set<string> = new Set([
  ...ANSWER_WORDS,
  "aahed", "aalii", "abaci", "aback", "abase", "abeam", "abhor", "abide",
  "abler", "abode", "aboon", "abash", "abbey", "abbot", "abdel", "abele",
  "abend", "abhor", "abide", "abies", "abner", "abode", "achoo", "acorn",
  "acrid", "adage", "adagio","added", "adder", "addio", "addle", "adept",
  "adjoin","adobe", "aegis", "aerie", "afoul", "agave", "agaze", "aging",
  "aglow", "agony", "agora", "agued", "ahem",  "aided", "aimer", "airy",
  "aisle", "aloft", "aloof", "aloud", "alpha", "altar", "amaze", "amber",
  "ample", "amply", "amuse", "ankhs", "annoy", "ansae", "antsy", "anvil",
  "aphid", "aping", "aptly", "arbor", "ardor", "ardent","areal", "ariel",
  "aptly", "askew", "aspen", "atoll", "atone", "atop",  "attic", "audio",
  "augur", "axiom", "baaed", "baste", "beard", "bayou", "bleak", "bliss",
  "booze", "brash", "brawn", "brawl", "breve", "briar", "brine", "brisk",
  "broil", "brood", "broth", "brunt", "budge", "bulge", "bumpy", "bylaw",
  "cabby", "caped", "cater", "cedar", "chafe", "champ", "chant", "chasm",
  "cheap", "cheer", "chide", "chimp", "chirp", "chive", "chock", "chomp",
  "chord", "cinch", "cited", "civet", "clamp", "clasp", "caulk", "cauls",
  "cleat", "cleft", "cleft", "clown", "clump", "clunk", "comet", "condo",
  "conga", "conk",  "cornea","could", "covet", "cramp", "creak", "creed",
  "creep", "crest", "crimp", "croak", "croon", "crumb", "cubed", "cubic",
  "cuckoo","curly", "cutie", "dally", "dandy", "decoy", "decry", "delve",
  "depot", "derby", "deter", "diver", "dizzy", "dodge", "dowel", "dozen",
  "droll", "drool", "dross", "druid", "duchy", "dully", "dunce", "dusky",
  "dwell", "easel", "elbow", "ember", "emoji", "emote", "empower","ennui",
  "envoy", "epoch", "equip", "ethic", "evade", "evoke", "exert", "expel",
  "expo",  "extol", "fable", "facet", "faker", "farce", "fared", "favor",
  "feral", "ferry", "fetid", "fiend", "fiery", "filth", "flair", "flank",
  "flap",  "flare", "fleck", "flick", "flung", "flute", "flyby", "foamy",
  "foggy", "foray", "forge", "forte", "foyer", "freak", "friar", "frond",
  "froth", "froze", "frugal","fungi", "fury",  "fuzzy", "gavel", "gauze",
  "gauzy", "gawky", "geyser","giddy", "gimme", "gizmo", "gland", "glean",
  "gloat", "gloss", "glyph", "gnash", "gnome", "gorge", "gouge", "gourd",
  "graft", "grail", "graze", "greed", "gruel", "gruff", "grunt", "guava",
  "guise", "gulch", "gully", "gummy", "gusto", "gypsy", "haiku", "haunt",
  "heady", "herby", "hertz", "hippo", "horde", "humph", "husky", "hydra",
  "hyena", "igloo", "impel", "inane", "inbox", "icing", "irked", "itchy",
  "jaunt", "jazzy", "jelly", "joust", "jubilee","kiosk", "kitty", "knack",
  "knave", "kneel", "knell", "knelt", "knick", "knobs", "knoll", "kooky",
  "lapse", "largo", "larva", "latch", "latte", "leafy", "leapt", "ledge",
  "leery", "lefty", "lemma", "libel", "liner", "lingo", "lofty", "lorry",
  "lousy", "lofty", "lusty", "lyric", "maxim", "melee", "mercy", "messy",
  "midway","minty", "mirth", "misty", "mimic", "mirth", "miser", "mitre",
  "mixed", "moldy", "molten","moody", "moped", "moron", "mossy", "mound",
  "muddy", "muggy", "murky", "musty", "myrrh", "nanny", "nasty", "nifty",
  "nimble","nippy", "nifty", "nitty", "nymph", "oakum", "odder", "offal",
  "often", "optic", "otter", "ovoid", "paddy", "pagan", "patsy", "perky",
  "petty", "peeve", "peppy", "perch", "physic","piggy", "piney", "pipette",
  "pixie", "plaid", "plait", "plank", "plasm", "pleat", "plied", "plonk",
  "plop",  "plume", "plunk", "poach", "poker", "poppy", "porky", "potty",
  "pouty", "prank", "prawn", "prism", "privy", "prowl", "prude", "psalm",
  "psych", "pudgy", "puffy", "punky", "punny", "pushy", "pygmy", "quaff",
  "qualm", "qualms","quark", "qualm", "rabbi", "racer", "rally", "reedy",
  "reeky", "repel", "rivet", "roast", "rodeo", "roomy", "roost", "rouse",
  "rowdy", "ruddy", "rusty", "sassy", "satyr", "savor", "savvy", "scald",
  "scalp", "scam",  "scone", "scoop", "scorn", "scrap", "scuff", "sedan",
  "seedy", "segue", "serum", "shack", "shaft", "shawl", "sheen", "sheer",
  "shelf", "shiny", "shrub", "shrug", "shuck", "shudder","skimp", "skunk",
  "skulk", "sloppy","slosh", "sloth", "slump", "slunk", "slurp", "soapy",
  "sonic", "spank", "spawn", "speck", "specter","spelt", "spook", "spore",
  "spout", "sprig", "spunk", "spurn", "stomp", "stork", "stoic", "stomp",
  "stout", "strap", "strew", "strut", "stunk", "stunt", "suave", "surly",
  "swath", "swirl", "swoop", "tacit", "talon", "tally", "taunt", "tawny",
  "tepid", "thatch","thong", "throb", "throe", "thud",  "thump", "tithe",
  "toxic", "topaz", "torso", "trite", "troll", "tromp", "troth", "troupe",
  "trout", "trove", "truce", "tunic", "twerp", "twirl", "twitch","udder",
  "undue", "unfit", "unify", "unruly","untie", "unzip", "upend", "vague",
  "vapid", "venal", "verge", "vigor", "viper", "vista", "voila", "vouch",
  "vroom", "wacky", "waltz", "warty", "waver", "weedy", "whelp", "whiff",
  "whirl", "whisk", "whomp", "whorl", "wimpy", "windy", "witty", "wobbly",
  "wordy", "woozy", "wrath", "wring", "wrote", "yearn", "zappy", "zappy",
  "zippy", "zombi", "zonal",
]);

export function getDailyWord(): string {
  const epoch = new Date("2024-01-01").getTime();
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime();
  const dayIndex = Math.floor((today - epoch) / (1000 * 60 * 60 * 24));
  return ANSWER_WORDS[dayIndex % ANSWER_WORDS.length].toUpperCase();
}

export function getRandomWord(): string {
  const word = ANSWER_WORDS[Math.floor(Math.random() * ANSWER_WORDS.length)];
  return word.toUpperCase();
}

export function isValidGuess(word: string): boolean {
  return VALID_GUESSES.has(word.toLowerCase());
}